name: miniCSR
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.28.1
  - pandas=2.2.3
  - tabulate=0.9.0
  - pyyaml=6.0.2
  - paramiko=3.5.0
  - pip
  - pip:
    - gunicorn=23.0.0
    - Flask=3.1.0
